version: 0.0
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - gem install bundler
                    - bundle install
                    - bundle exec jekyll build
        artifacts:
            files:
                - _site/**/*